### ISSUE TITLE
Paginación

### ISSUE THREAD

**Issue by arieljolo** [sysarmy/blog#1]
No estaría encontrando la paginación para ir a blogs anteriores

**Comment by axelvf** [comment]
Hice unas pruebas y no me funcionó. Tengo que investigarlo un poco mas, por el momento se muestran todos los posts en home.

**Comment by axelvf** [comment]
![image](https://user-images.githubusercontent.com/10050288/79188397-44072580-7df5-11ea-8f7a-d3d463ba7139.png)
Arreglado después de mucho tiempo!
@ajolo2ky @edux
