### ISSUE TITLE
consulta ejemplo

### ISSUE THREAD

**Issue by edux** [sysarmy/blog#10]
en https://github.com/sysarmy/blog/blame/serie-docker/content/posts/docker-comandos-basicos-primera-parte.md#L90 no deberia ser sysarmy_docker para continuar el hilo del ejemplo?

**Comment by gacanepa** [comment]
@edux Usé **silly_tesla** en el ejemplo de detener y borrar para no perder el **sysarmy_docker**. Avisame si te cierra o si sugerís un cambio o aclaración.

**Comment by edux** [comment]
tire el comment porque si venis probando ya tenes creado silly_tesla? como
para que si alguien sigue el tutorial al pie no ejecute algo que le vaya a
fallar. ese es mi comment nomas.
