### ISSUE TITLE
Deploy del blog roto

### ISSUE THREAD

**Issue by Nachichuri** [sysarmy/blog#108]
@axelvf @edux para cuando tengan 5min, está roto el workflow que hace el deploy del blog, entiendo porque la branch `gh-pages` está protegida.

Por lo que veo [acá en el log del job](https://github.com/sysarmy/blog/actions/runs/4339930718/jobs/7578044902#step:4:65), no está pudiendo hacer el push a la branch:

```
Switched to a new branch 'gh-pages'
Files to Commit:11
remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.        
remote: error: Cannot force-push to this branch        
To github.com:sysarmy/blog.git
 ! [remote rejected] gh-pages -> gh-pages (protected branch hook declined)
error: failed to push some refs to 'github.com:sysarmy/blog.git'
=================== Done  ===================
```

Entonces después el job de [Push](https://github.com/sysarmy/blog/actions/runs/4339930718/jobs/7578045080) rompe porque no ve cambios para hacer el deploy.

Creo que vendría por ahí el problema, no sé si se cambió la config de protected branches, no tengo acceso a las configs del repo, me resulta raro porque el [post con los resultados de la encuesta buildeó bien](https://github.com/sysarmy/blog/actions/runs/4294448235/jobs/7483486502#step:4:64).

**Comment by axelvf** [comment]
Hola @Nachichuri gracias por el aviso. Si, se protegió la branch para evitar que se eliminara, pero algun otro permiso se ve que le faltó habiltar. De todos modos, quité nuevamente la protección y corrí los jobs nuevamente y corrieron correctamente. https://github.com/sysarmy/blog/actions/runs/4341551933
Cuando vuelva a habilitarlo hago una prueba de build completo y te aviso para que también estes en conocimiento.
Gracias nuevamente! cc @edux
