### ISSUE TITLE
Galería de imágenes

### ISSUE THREAD

**Issue by arieljolo** [sysarmy/blog#2]
Habría que instalar una galería, para que al clickear las imágenes no vayan al archivo jpg directo. En los otros blogs que tengo instalé https://github.com/liwenyip/hugo-easy-gallery, que recién veo que está medio deprecado, habría que ver si tiene sentido instalar éste o ver algún otro.

**Comment by axelvf** [comment]
Volví @arieljolo!
Parece que el llamado a la comunidad hizo que la reactiven, quedó instalado, hice unos cambios para no tener que llamarla en cada post. Solo habría que referenciarla de la siguiente manera:
{{< figure src="assets/image.png" link="assets/image.png" >}}

Post utilizándola: 
content/posts/como-funciona-netflix-el-complejo-proceso-en-terminos-sencillos-que-se-pone-en-marcha-cada-vez-que-reproducis-un-video.md

**Comment by axelvf** [comment]
Actualizado el post de Ramón:
https://sysarmy.com/blog/2015/12/14/armando-a-ramon/

**Comment by axelvf** [comment]
Posts con muchas imágenes pasaron a galería
