### ISSUE TITLE
sirve tener esto como submodulo?

### ISSUE THREAD

**Issue by edux** [sysarmy/blog#21]
porque hay que actualizarlo manualmente en sysarmy.github.io en cada update del blog, quizas conviene cambiarlo a que sea un rsync, add y push adentro del action?

**Comment by edux** [comment]
Quizas es para agregar un action en el blog que sea un checkout del website, y un 

git submodule update --remote
git add git push

**Comment by axelvf** [comment]
Voy a ver de armar un action que haga ese update. Dejame que lo piense un poco :)

**Comment by edux** [comment]
Fixed ahi quedo andando. que pedazo de garcha que son las github actions.
