### ISSUE TITLE
Migración a nuevo theme

### ISSUE THREAD

**Issue by axelvf** [sysarmy/blog#27]
Estoy viendo que el theme actual tiene muchos parches y se ve bastante mal en mobile.
Hay uno que estuve chusmeando y es bastante simple para lo que necesitamos: https://github.com/panr/hugo-theme-hello-friend

Lo importé al proyecto actual para evaluar factibilidad y ver que tenemos que fixear. En primera medida lo dejé lo mas parecido en cuanto a funcionalidades con el actual. Post, imagen, tags, tiempo de lectura, etc.

Algunos temas que detecté son:

- [X] Estandarización de URLs: Los posts nuevos no tienen la fecha en la URL (que me parece lo correcto) https://sysarmy.com/blog/posts/resultados-de-la-encuesta-de-sueldos-2021-1/ y los mas viejos https://sysarmy.com/blog/2015/01/09/s02e01-open-papa/. 

- [X] Estandarización de imagenes: Al cambiar el theme las imagenes de algunos posts estan rotas por la URl relativa. Me pongo a corregirlas

- [X] Importar imagenes: Hay muchas imagenes que son links externos y pueden romperse los posts si estas las eliminan, voy a importarlas a /assets/ 

Layouts:

- [X] Veeam

- [x]  Analytics: Esta el codigo pero el tag esta comentado desde config.

- [x] Comentarios: Migrar script de comentarios de FB. 

Lo que fui probando quedó en una nueva branch llamada new-theme para que puedan revisarlo.

**Comment by axelvf** [comment]
> * Estandarización de URLs: Los posts nuevos no tienen la fecha en la URL (que me parece lo correcto) https://sysarmy.com/blog/posts/resultados-de-la-encuesta-de-sueldos-2021-1/ y los mas viejos https://sysarmy.com/blog/2015/01/09/s02e01-open-papa/.
>   Cual seria el camino a seguir?
Fixed

**Comment by axelvf** [comment]
> * Estandarización de imagenes: Al cambiar el theme las imagenes de algunos posts estan rotas por la URl relativa. Me pongo a corregirlas

Fixed

**Comment by axelvf** [comment]
> * Importar imagenes: Hay muchas imagenes que son links externos y pueden romperse los posts si estas las eliminan, voy a importarlas a /assets/

Fixed

**Comment by edux** [comment]
Los comentarios de FB no van mas, ahi meti un commit con el codigo de vanilla que es lo que usamos hoy. Pasa que para probarlo hay que mandarlo a prod, tampoco es tan importante asi que puede salir despues.

respecto de veam veo que sale 2 veces en el footer, eso esta ok?

agregue un par de links al header tambien. yo creo que podemos sacarlo asi e ir refinando en prod.

**Comment by axelvf** [comment]
Si, creo que no tenemos forma de probarlo localmente. 
Incluso asumo que lo de Veeam aparece 2 veces por lo mismo, es el mismo código de prod.
Esta noche si no aparecen nuevas cosas, lo paso a master y vamos puliendo

**Comment by axelvf** [comment]
> * [ ]  Comentarios: Migrar script de comentarios de FB.

Publicado!!
Se cambia por Vanilla. Esta funcionando. Solo agregaria un paginado para que tenga un titulo como "Leer otros posts". 
<div class=pagination><div class=pagination__title><span class=pagination__title-h>Comentarios</span><hr></div>

El "Deja un comentario" mepa que viene del js porque en dark apenas se lee.

**Comment by edux** [comment]
si, el vanilla es una porqueria. en algun momento tengo que migrar a
discourse.
