### ISSUE TITLE
doble tag manager.

### ISSUE THREAD

**Issue by edux** [sysarmy/blog#41]
<img width="1084" alt="Screen Shot 2021-04-20 at 23 05 52" src="https://user-images.githubusercontent.com/857187/115486432-07061800-a22d-11eb-819d-14c7fb3d57ad.png">

mi duda es si el que esta con help viene de help o esta en el template del blog? porque yo lo agregue bien al layout para que se vea en la home tambien, pero no encuentro donde esta para que salga en el div de /help

**Comment by axelvf** [comment]
@edux Empezó a aparecer cuando agregué los comentarios de Vanilla, para mi ahi se inyecta.
