### ISSUE TITLE
oncall para empresas sin impresoras de dinero.

### ISSUE THREAD

**Issue by edux** [sysarmy/blog#45]
https://www.softwareatscale.dev/p/manageable-on-call-for-companies

**Comment by Nachichuri** [comment]
buenas, estuve leyendo este artículo y me pareció copado, si querés asignamelo y lo traduzco para que salga en abril

**Comment by Nachichuri** [comment]
Buenas, ahí agregué la tradución para un nuevo post, dejé placeholder para reviewer.

Quizás estaría bueno dejar la publicación para más adelante tipo abril?

**Comment by Nachichuri** [comment]
Published :)
