### ISSUE TITLE
cambiar el comment backend a github

### ISSUE THREAD

**Issue by edux** [sysarmy/blog#71]
Actualmente los comments van a parar a hilos de help, aunque basicamente no los usa nadie. me cruce con esto https://github.com/utterance/utterances y me parece que seria piola para integrarlo a este repo y desacoplarlo de help.

**Comment by Nachichuri** [comment]
Buenas, pensaba probar esto, estuve viendo que la implementación sería relativamente sencilla. Cuando tenga algo pingueo por acá (:

**Comment by edux** [comment]
fijate, nose si tiene mucho sentido, tambien esta https://disqus.com/, ojo y tambien esta el tema de qeu quizas ni tiene sentido habilitar comments en el blog porque nadie los uso jamas. sencillamente quizas es mejor removerlos.

**Comment by Nachichuri** [comment]
Buen punto, no sé, de todas maneras me parece que tanto _disqus_ como _utterances_ serían un poco más user friendly que lo que hay hoy... si suena útil probamos si genera mas engage y si no se usa directamente los volamos?

**Comment by edux** [comment]
@axelvf thoughts?

**Comment by axelvf** [comment]
@edux Esta bueno el resumen de @Nachichuri, yo creo que nadie usó la funcionalidad de comentarios desde que tenemos FB. Esta piola que sea amigable y fácil de implementar lo de Github, pero realmente lo usara la gente? porque hay que llevar una administracion de esto también.

**Comment by edux** [comment]
Fue, en el espiritu de simplificar removamos los comentarios completamente y listo.
