### ISSUE TITLE
oncall compensation

### ISSUE THREAD

**Issue by edux** [sysarmy/blog#86]
https://blog.pragmaticengineer.com/oncall-compensation/ para traer al español.

**Comment by jcasarini** [comment]
Buenas!
Me pongo con esto.
Una vez que está traducido pasa a revisión? Hay algún instructivo/template?

**Comment by edux** [comment]
Buenas, sí acá https://github.com/sysarmy/blog/blob/master/readme.MD están las instrucciones para mandar el pull request al repo, tenés que hacer un fork del blog, y mandar un pull request.

**Comment by jcasarini** [comment]
Ya tengo la traducción lista, 28 páginas, no terminaba más! Ya está en markdown, ahora me falta la parte de github que no usé nunca en mi vida, jajaja

**Comment by Nachichuri** [comment]
Genial! [Acá te dejo una guía](https://github.com/firstcontributions/first-contributions/blob/main/translations/README.es.md) que está bastante step by step de cómo hacerlo, igual si te trabas me pingueas por Discord y lo vemos!

**Comment by edux** [comment]
Felicitaciones por hacer la milla extra y arrancar con github!

**Comment by jcasarini** [comment]
Gracias @edux!

**Comment by edux** [comment]
publicado.
